SDU-eScience/UCloud

backend/storage-service/api/src/main/kotlin/FileDescriptions.kt
backend/storage-service/build.gradle.kts
backend/storage-service/k8.kts
backend/storage-service/src/main/kotlin/file/http/ActionController.kt
backend/storage-service/src/main/kotlin/file/services/LimitChecker.kt

Changes variable names for Quota class and added check on quota allocations for subproject when changing project allocation. Used so that a project cannot be lower to more than it already have allocated it self (no over allocation). This should also remove all problems and fix #1909 .
There have not been create a potential script for projects were allocation is already overallocated.

Quota cleanup

---

frontend-web/webclient/app/Applications/Jobs/Shell.tsx
frontend-web/webclient/app/Applications/Jobs/View.tsx
frontend-web/webclient/app/Applications/Jobs/Vnc.tsx

- Improved the View UI for single node applications (fixes #2194)
- Renamed "Rank(s)" and "Replica(s)" to "Node(s)" in the locations I could find the occurrences (fixes #2189)

Improved UI for single node applications + renaming to "node(s)"

---

backend/auth-service/src/main/kotlin/auth/services/UserAsyncDAO.kt
backend/ucloud-data-extraction-service/src/main/kotlin/services/UserActivityReport.kt

We had an issue when creating a WAYF user. Perhaps due to retires there was two users created before we could check, resulting in null value (singleOrNull). This fix makes a check in insert function if the user is from WAYF to check on WAYFID instead of our user generated ID this should make the situation more unlikely.

attempt to fix wayf user creation issue

---

frontend-web/webclient/app/Files/LowLevelFileTable.tsx
frontend-web/webclient/app/Files/QuickLaunch.tsx

Fixes the Quick Launch feature (it haven't been working for a while), and adds a pop-up/modal in case the user have credit available for multiple machines, allowing the user to select which machine to use.
In case the user only have access to 1 machine, the machine will be chosen and launched automatically (as before).
fixes #2247

Quick Launch fixed with option to select machine

---

backend/app-orchestrator-service/src/jvmMain/kotlin/services/JobFileService.kt
backend/app-orchestrator-service/src/jvmMain/kotlin/services/JobMonitoringService.kt
backend/storage-service/api/src/commonMain/kotlin/PathUtils.kt

fixes #2294 
Also fixes a bug in in the `joinPath` utility function, which caused output folders to be created/saved with double `/`, i.e. `/home/user/Jobs/Coder/12345/` would be saved as `/home/user//Jobs//Coder/12345/` because of how `joinPath` joined paths with trailing `/` together.

Fixed incorrect last_scan timestamp and output folder path for jobs

---

backend/project-service/api/src/commonMain/kotlin/Projects.kt
backend/project-service/build.gradle.kts
backend/project-service/k8.kts
backend/project-service/src/jvmMain/kotlin/project/rpc/ProjectController.kt
backend/project-service/src/jvmMain/kotlin/project/services/ProjectService.kt
frontend-web/webclient/app/Project/Subprojects.tsx

Parent Projects can now always rename subprojects. Projects themself are stil only allowed to rename if parent allows. Fixes #2132

RenamingIssue

---

backend/indexing-service/build.gradle.kts
backend/indexing-service/k8.kts
backend/indexing-service/src/jvmMain/kotlin/indexing/services/FileSystemScanner.kt

Added check for file .skipFolder when entering a directory.
If file is present it skips the entire folder and subfolders.
Fixes #2375

Index break

---

frontend-web/webclient/app/Core.tsx
frontend-web/webclient/app/Files/Files.tsx
frontend-web/webclient/app/Navigation/Header.tsx
frontend-web/webclient/app/Resource/Router.tsx

Should fix missing redirection. However, I'm not sure if there's a reason the `component={ComponentName}` approach wasn't used here.

Fixes #2729

---

frontend-web/webclient/app/Files/Metadata/Documents/History.tsx
frontend-web/webclient/app/Files/Metadata/JsonSchemaForm.tsx

I've tried to make a few improvements to the metadata UI.
In particular:
- fixes #3041 . Although I think it makes sense to remove the "description" from the favorites metadata template, and make sure that titles have a upper-case starting letter (in the database).
- As mentioned in #2882 there's some weird behavior on the "New document" and "Close document" buttons. I've attempted to fix this by:
- By default the active/most recent document is shown
- "New document" opens the new document editor
- "Close new document" returns to the most recent document
- Saving a new document goes to the most recent document, instead of displaying the new document editor.

Minor improvements to metadata UI

---

backend/file-ucloud-service/src/jvmMain/kotlin/rpc/FilesController.kt
backend/file-ucloud-service/src/jvmMain/kotlin/services/FileQueries.kt

Add error message if file/folder already exists when creating a new folder, or when renaming a file/folder.
fixes #3059

Error message on file/folder conflicts

---

frontend-web/webclient/app/UCloud/ResourceApi.tsx

Issue #3137 was already partly fixed by a21d7fc6f198f10e99b50247e0cf730d8cfa5d0d but it removed the cancel button entirely in the embedded context.
fixes #3137

Allow cancel of creation of resource in embedded browse

---

frontend-web/webclient/app/Files/Preview.tsx

- Show error in file preview if file is empty
- Fixed bug where file preview error would never show, but just show loading icon
fixes #3147

Fix file preview error bugs

---

frontend-web/webclient/app/Resource/Browse.tsx

"Fixes" #3158 by disabling the useScrollStatus as this causes the reload. I think it adds too little to keep it in compared to the bug.

Fixes #3158

---

frontend-web/webclient/app/Project/Grant/GrantApplicationEditor.tsx

Previously, `loading` was set true when `invokeCommand` was called, which is pretty far down in the `submit`-call. Instead, a different boolean is used, and set right when the call is made, and set to false when the `submit` call terminates in any way.

Fix for #3154

---

backend/accounting-service/src/jvmMain/resources/db/migration/V27__Issue3248Charge.sql
backend/integration-testing/src/jvmTest/kotlin/backend/Accounting.kt

When charge was checking for failed charges the returning statment of the updates subtracted the needed amount again from the return value. The returning values is using the postupdate values and therefore it would fail once 1/2 of the available resources was required.
Have tested manually
- standard small charge
- charge that would result in negative
- adding new allocation after overchage and making new charge afterwards.
This works as expected both for Differential products and Absolute.
Also made small test suite

Fix to charge code

---

backend/file-ucloud-service/src/jvmMain/kotlin/rpc/SyncController.kt
backend/file-ucloud-service/src/jvmMain/kotlin/services/SyncService.kt
backend/file-ucloud-service/src/jvmMain/kotlin/services/SyncthingClient.kt
compose/base.yml
launcher

Currently we are using a single main-call for (almost) all communication with Syncthing (`writeConfig`) which will fetch all devices and folders, generate a Syncthing config which will then be sent to Syncthing. However, requesting Syncthing to overwrite its config appears to make it restart (including the API server). Because of this we experience a lot of communication problems between the kTor client and Syncthing.
This PR includes implementations for less drastic calls to Syncthing, meaning that we will instead only use `writeConfig` when the service (provider) is started. Instead it will be left to Syncthing to generate/update its configuration internally using the following calls: `addFolders`, `addDevices`, `removeFolders`, `removeDevices`.
`addFolders` and `addDevices` will still …

Syncthing fixes

---

frontend-web/webclient/app/Syncthing/Overview.tsx
frontend-web/webclient/app/UCloud/FilesApi.tsx
frontend-web/webclient/app/ui-components/Tooltip.tsx
frontend-web/webclient/package-lock.json
integrated-applications/syncthing/Dockerfile

- "Remove" button (for folder) renamed to "Remove from Sync",
- added warning modal for "Factory reset" button,
- click on synchronized folder takes you to the folder (+ removed "Open folder" option from folder operations),
- added user with name "syncthing" to the app container,
- added warning to synchronized folders which might contain files which isn't sync-able,
- prevent adding the same folder to Syncthing more than once,
- hide sync button from shares,
- prevent adding (incoming) shared folder to sync from the sync ui.
fixes #3430
fixes #3433

Improvements and fixes for Syncthing

---

frontend-web/webclient/app/Applications/Jobs/Create.tsx
frontend-web/webclient/app/Applications/Jobs/View.tsx
frontend-web/webclient/app/Syncthing/Overview.tsx
integrated-applications/syncthing/src/main/kotlin/syncthing/SyncthingClient.kt
integrated-applications/syncthing/src/main/kotlin/syncthing/UCloudConfigService.kt

Added price/hour to runs page (fixes #3542)
Redirect to Manage Synchronization-page on open Syncthing-app from App store (fixes #3541)
Remove "Default folder" created by Syncthing on first start (fixes #3540)
Disable password warning in Syncthing GUI by setting `insecureAdminAccess` to true (fixes #3539)
Changed "Syncthing Servers" headline to "Syncthing Server" (singular) if there's only one server (fixes #3536)
Removed "Upgrade" button from Syncthing GUI by removing the `releasesURL` used to check for updates (fixes #3535)

Minor fixes for Syncthing

---

backend/app-kubernetes-service/src/jvmMain/kotlin/rpc/AppKubernetesController.kt
backend/app-kubernetes-service/src/jvmMain/kotlin/services/UtilizationService.kt
backend/app-orchestrator-service/api/src/commonMain/kotlin/JobsProvider.kt
backend/app-orchestrator-service/src/jvmMain/kotlin/services/JobOrchestrator.kt

Updates `UtilizationService` methods to take a product parameter, returning queue status, capacity and usage of nodes flagged with that product only (instead of the whole cluster). In case no nodes is found, the service will return for the whole cluster (as before).
The call from app-orchestrator have been updated to send the name of the product category.
fixes #2425

Product/category parameter for retrieveUtilization

---

frontend-web/webclient/app/Project/ProjectSettings.tsx
frontend-web/webclient/app/Project/SubprojectList.tsx
frontend-web/webclient/app/Project/cache.ts
frontend-web/webclient/package-lock.json
frontend-web/webclient/package.json

Changes:
```
setAllowRenaming(getRenamingStatus({projectId: props.projectId}))
```
to
```
setAllowRenaming(getRenamingStatusForSubProject({projectId: props.projectId}));
```
for ProjectManagement page
and  adds an isAdminOrPI check for currently active project. I'm not sure that the right side of the predicate event makes sense to have on the SubprojectList page.
```
enabled: (selected, extras) => {
if (selected.length !== 1) return false;
if (extras.isAdminOrPIForParent || isAdminOrPI(selected[0].role ?? ProjectRole.USER)) {
return true;
} else {
return "Only Admins and PIs can rename.";
}
}
```

Fixes #3615

---

provider-integration/integration-module/src/main/kotlin/config/VerifiedConfig.kt
provider-integration/integration-module/src/main/kotlin/plugins/storage/posix/PosixCollectionPlugin.kt
provider-integration/integration-module/src/main/kotlin/sql/migrations/Index.kt
provider-integration/integration-module/src/main/kotlin/sql/migrations/PosixStorage.kt

fixes #3661 
fixes #3691 
Corrects accounting for non-quota storage products.
For each charge the Posix plugin will calculate the time of the end of the charged period and save it. The next time the collection is scanned, the number of periods are calculated from this timestamp, the charge is made, and the time of the end of the charge is overwritten.
An example for a non-quota storage resource which is charged hourly, with a filesystem scan every 1.5 hours:
- First scan: The current timestamp is saved to denote the beginning of the first period.
- Second scan: The plugin calculates the time between the beginning of the first period and now to be 1 period, makes a charge, and updates the timestamp to be 0.5 hours earlier.
- Third scan: The plugin calculates the time between the last …

Accounting for Posix plugin (non-quota)

---

frontend-web/webclient/app/Authentication/DataHook.ts
frontend-web/webclient/app/Project/Allocations.tsx
frontend-web/webclient/app/Project/Api.tsx
frontend-web/webclient/app/Project/SubAllocations.tsx
frontend-web/webclient/app/Resource/Browse.tsx

Add async to useCloudAPI. Can now be awaited, but is opt-in. Fixes #3144
Don't update allocationGeneration until backend responded. Fixes #3723
Use correct projectId for new recipients (suballocations). Fixes #3765

Remove console logs (I don't think they were being used at all)

---

frontend-web/webclient/app/Dashboard/Dashboard.tsx

Minor fixes to make dashboard cards more consistent with regards to spacing and buttons.
- Changed "View applications" from link to button in "Recent runs card
- Empty cards show small (not full-width) button below description
- Consistent spacing between buttons and descriptions
- "Apply for resources" button on Grant applications card changes to full-width if not empty

Dashboard fixes

---

backend/accounting-service/util/src/main/kotlin/ResourceService.kt
backend/app-orchestrator-service/src/main/kotlin/services/JobOrchestrator.kt

Properly unbind ingresses, network IPs and licenses if the provider fails on creating the job, by removing the job id from `status_bound_to` in the corresponding tables.
This allows using ingresses again if the job fails (fixes #3165)
Also delete anything from `job_input_parameters` and `job_resources` associated with the failed job (fixes #3244).

Unbind ingresses, network ips and licenses on job creation failure + cleanup

---

backend/app-store-service/src/main/kotlin/app/store/api/ApplicationDescription.kt
frontend-web/webclient/app/Applications/Jobs/Widgets/Bool.tsx
frontend-web/webclient/app/Applications/Jobs/Widgets/Enum.tsx
frontend-web/webclient/app/Applications/Jobs/Widgets/GenericText.tsx
provider-integration/integration-module/src/main/kotlin/plugins/compute/slurm/SBatch.kt
provider-integration/integration-module/src/main/kotlin/plugins/compute/ucloud/FeatureParameter.kt

- Default values should be passed correctly by the provider,
- On the frontend:
- default values should be automatically inserted into the input fields of some parameter types (text, integer, floating_point), and selected automatically in case of enums and booleans,
- min, max and step should now work correctly for integers and floating_point,
- entering text in a integer or floating_point parameter field should show that the input is invalid (in firefox) or not be possible at all (chrome).
Marking as draft until the support team have tested the changes + we have discussed whether numeric fields should remain as text-fields or be changed to number fields.
ref #3308

defaultValue pass by provider + frontend usage of defaultValue

---

backend/accounting-service/src/main/kotlin/services/grants/Notifications.kt

It seems users were receiving multiple identical emails whenever a grant-application was created or updated.
The number of emails send to each user seemed to depend on the number of products applied for (1 email for each product of the application, to each admin).
There might be a better fix, and I suspect the bug is located elsewhere. This PR just ensures that the list of receivers for a notification does not contain duplicates, which seems to fix the problem.

Fixed emails being send multiple times to same receiver

---

frontend-web/webclient/app/Files/Preview.tsx
frontend-web/webclient/app/UtilityFunctions.tsx
frontend-web/webclient/package-lock.json
frontend-web/webclient/package.json

Improves preview of files, with the two main changes:
- Use magic bytes ([magic-bytes.js](https://github.com/LarsKoelpin/magic-bytes)) to determine the file type, instead of the file extension. Preview of files should now work in most cases, independently of the extension. 
- Switch to [monaco-editor](https://microsoft.github.io/monaco-editor/) for preview of text (set to read-only mode). The editor includes more features like file-search and better performance. The 100kb limit on syntax highlighting has been removed since it seems monaco has build-in limits. Monaco is not able to determine the file type, so we try to guess the file type from the extension and pass it to monaco.
fixes #4066

Improvements to file preview

---

backend/file-orchestrator-service/util/src/main/kotlin/FileCollectionService.kt
provider-integration/integration-module/src/main/kotlin/plugins/compute/ucloud/FeatureFileMount.kt
provider-integration/integration-module/src/main/kotlin/plugins/compute/ucloud/Plugin.kt

Mounts of drives are translated to drivenames instead of id.
Also contains a restriction to creation of drives. From now on users cannot create drive with same name within same provider

Id inmount issue

---

frontend-web/webclient/app/ui-components/ResourceBrowser.tsx

Attempted to fix #2980 but it seems already fixed.
However noticed that the search bar does not show all drives/shares and ignores enter, when search field is empty. So changed this

Search searches on empty search

---

backend/app-orchestrator-service/src/main/kotlin/services/JobVerificationService.kt

Check if job is VM and set allocated time to null if set. Frontend currently sets automatically 1 hour on create
Fixes #4090
Tested on launcher env with changing directly in DB with normal app and with code (by excluding new if)
If statement should only catch VMs after tested

Fix to exprie times on VMs

---

frontend-web/webclient/app/Applications/Jobs/Create.tsx
frontend-web/webclient/app/UserSettings/ChangeEmailSettings.tsx

fixes #4179 
- Added the option to "Notify me  when a job stops"
- Link the select box to the backend
- Automatically detect what the current setting is, and set as default value
This changes the global settings, not on a per-job basis, but I think it should be clear from the wording and behavior.

Change email notifications from create job page

---

frontend-web/webclient/app/ui-components/ConfirmationAction.tsx

This may be an overcorrection, but it seems like the text color is always white, so the tick and the progress-circle should match that

Fixes #4199

---

backend/accounting-service/src/main/kotlin/services/grants/GrantsV2Service.kt
frontend-web/webclient/app/Grants/Editor.tsx

Fixed #4279 . Also made comment section auto scroll down to newest revision or comment.
Only shows transfer options based on grant seekers available grant givers (not included those already in the grant).
Might be a better way for the frontend to show the possible transfer options than the new element "possibleTransfers" identical to "allcoators", but the "allocators" element was filtered and modified to only contain the allocators that was requested for resources in the grant, so it did not contain all possible grant givers of the grant seeker.
Not sure if it should be possible to transfer to a grant giver that is already participating in the grant. If it should be possible should the resources that overlap then just be summed or should something else happen?

Grant Transfer update

---

frontend-web/webclient/app/Accounting/index.ts

Fixes #4451 
Not posssible to show limitation of resource on the overview of a sub-project since the info is not available.
See Note from Dan on line 1011 in changed file (index.ts)

fixes color issue

---

frontend-web/webclient/app/UCloud/FilesApi.tsx

Fix wrong `next` being passed fetching the next files for large pages

---

frontend-web/webclient/app/UCloud/FilesApi.tsx

Fixes #4545

---

provider-integration/integration-module/src/main/kotlin/plugins/compute/ucloud/FeatureIngress.kt
provider-integration/integration-module/src/main/kotlin/plugins/compute/ucloud/FeaturePublicIP.kt

Quick fix to relieve support. 
Removes job monitoring on ingres and public IP. No more charges or kills should be made in the loops.
Need better solution 
#4583

remvoed monitoring of ingress and publicIP

---

backend/accounting-service/src/main/kotlin/Main.kt
backend/accounting-service/src/main/kotlin/Server.kt
backend/accounting-service/src/main/kotlin/services/accounting/LowFundsJob.kt
backend/accounting-service/src/main/kotlin/services/accounting/Messages.kt
backend/accounting-service/src/main/kotlin/services/accounting/Model.kt
backend/accounting-service/src/main/kotlin/services/accounting/Persistence.kt
backend/accounting-service/src/main/kotlin/services/accounting/System.kt
backend/accounting-service/src/main/resources/db/migration/V68__LowBalance.sql

Fixes #4864. Checks if remaining resource is below certain threshold on wallets level. Does not warn if maxusable is getting to low, since this case should be handled by the parents getting this perticular email and acting on it.

Mail low funds check

---

frontend-web/webclient/app/Providers/ConnectionState.tsx

Increases timeout so less hammering on the system by connected clients when something goes down.

Increase timeout duration #3995

---

frontend-web/webclient/app/Accounting/index.ts
frontend-web/webclient/app/ui-components/Progress.tsx

Fixes #4971 and moves warning triangle above progress bar on the allocations page.

Frontend: fixes #4971 and moves warning triangle above progress bar.
