SDU-eScience/UCloud

- backend/auth-service/src/main/kotlin/auth/services/UserAsyncDAO.kt
- frontend-web/webclient/app/UserSettings/ChangePassword.tsx
- frontend-web/webclient/app/UserSettings/ChangeUserDetails.tsx
Disallows updating first names, last names and e-mail to be empty, both in front-end and backend.
> Fixes #2015

- backend/mail-service/api/src/main/kotlin/MailDescriptions.kt
- backend/mail-service/src/main/kotlin/mail/rpc/MailController.kt
- backend/mail-service/src/main/kotlin/mail/services/MailService.kt
- backend/slack-service/api/src/main/kotlin/Ticket.kt
- backend/slack-service/src/main/kotlin/services/SlackNotifier.kt
- backend/support-service/api/src/main/kotlin/SupportDescriptions.kt
- backend/support-service/build.gradle.kts
- backend/support-service/src/main/kotlin/support/http/SupportController.kt
- backend/support-service/src/main/kotlin/support/services/TicketService.kt
- backend/support-service/src/test/kotlin/support/http/SupportTest.kt
- backend/support-service/src/test/kotlin/support/services/TicketServiceTest.kt
- frontend-web/webclient/app/ui-components/SupportBox.tsx
Adds subject field to support tickets and forward tickets to support@escience.sdu.dk as well as slack.
This have not been tested since localhost gets 404 on send slack and dev does not work.
If works will fix #1999
> Support jira intergration

- frontend-web/webclient/app/Applications/Jobs/View.tsx
> Show time remaining in Job/View UI

- frontend-web/webclient/app/Project/Grant/GrantApplicationEditor.tsx
> Hide empty sections in grant application editor

- backend/storage-service/build.gradle.kts
- backend/storage-service/k8.kts
- backend/storage-service/src/main/kotlin/file/services/BulkUploadService.kt
Changed to Apache common compress.
Tested with failing tars from previous release - now works.
Zip still works after change (also with big files)
> changed to Apache common compress and tested on dev

- frontend-web/webclient/app/Applications/Jobs/Browse.tsx
- frontend-web/webclient/app/ui-components/Operation.tsx
- Added borders to job elements,
- added header,
- decreased font size and centered text on Cancel button.
fixes #2196
> Make Runs UI more consistent with Files UI

- backend/accounting-service/src/main/kotlin/services/Products.kt
> Fixed hiddenInGrantApplications not saved when creating license server

- backend/app-kubernetes-service/src/main/kotlin/rpc/ShellController.kt
> Change order of shells used

- frontend-web/webclient/app/Applications/Jobs/View.tsx
Note: The warning is only shown once on "confirm", but will be shown again if:
- the page is reloaded or,
- if the user presses "cancel".
This was not intended, but I think it makes sense in this context. I can change this behavior if needed.
fixes #2195
> Warning if a job is extended beyond what the balance allows

- frontend-web/webclient/app/Applications/Jobs/View.tsx
Happened for single node applications only.
fixes #2232
> Fixed unintentional auto-scroll on job view UI

- frontend-web/webclient/app/ui-components/ConfirmationAction.tsx
- frontend-web/webclient/app/ui-components/Operation.tsx
> Hold-to-confirm button styling

- backend/app-orchestrator-service/src/main/kotlin/services/JobVerificationService.kt
> Prevent submission of job with 0 time allocated

- frontend-web/webclient/app/Applications/Overview.tsx
> Refreshing of app overview + Removed caching of favourites

- backend/app-kubernetes-service/src/jvmMain/kotlin/services/ExpiryPlugin.kt
> Fixed calculation errors on extendJob

- backend/integration-testing/src/jvmTest/kotlin/backend/Projects.kt
- backend/project-service/src/jvmMain/kotlin/project/services/ProjectService.kt
- backend/project-service/src/jvmMain/resources/db/migration/V19__RootProjectConstraint.sql
- backend/service-lib-server/src/jvmMain/kotlin/service/db/async/SQLErrorCode.kt
Adds a test and and constraint to disallow root projects to share a title.
> Fixes #2284

- backend/app-store-service/build.gradle.kts
- backend/app-store-service/k8.kts
- backend/app-store-service/src/main/kotlin/app/store/services/AppStoreAsyncDao.kt
- backend/app-store-service/src/main/kotlin/app/store/services/ApplicationLogoAsyncDao.kt
- backend/app-store-service/src/main/kotlin/app/store/services/ApplicationPublicAsyncDao.kt
- backend/app-store-service/src/main/kotlin/app/store/services/ApplicationSearchAsyncDao.kt
- backend/app-store-service/src/main/kotlin/app/store/services/ApplicationSearchService.kt
- backend/app-store-service/src/main/kotlin/app/store/services/ApplicationTagsAsyncDao.kt
- backend/app-store-service/src/main/kotlin/app/store/services/FavoriteAsyncDao.kt
Introduces lowercase to all name and versions for new DB entries (Matches ES)
New Search query.
> Fixes #2310 and Fixes #2293

- backend/app-kubernetes-service/build.gradle.kts
- backend/app-kubernetes-service/k8.kts
- backend/service-lib-server/src/jvmMain/kotlin/service/k8/KubernetesClient.kt
> Use ca.crt for trust when connecting to k8

- frontend-web/webclient/app/Applications/Jobs/View.tsx
Seemed to be caused by an uncaught type error, but only happened some times, when on the JobView page while the job expired.
Ref. #2274 , but I'm not sure it's a fix.
> Fix frontend crash when job expires

- backend/grant-service/src/jvmMain/kotlin/grant/services/Applications.kt
- frontend-web/webclient/package-lock.json
Found issue with only checking credits and not quota resulting in project being created and then failing due to missing quota. Inserted qouta check after resource check before proceeding. Fixes #1990
> Attempt to fix resource check on approve of application

- backend/activity-service/src/jvmMain/kotlin/activity/services/ActivityEventElasticDao.kt
- backend/alerting-service/build.gradle.kts
- backend/app-orchestrator-service/build.gradle.kts
- backend/app-store-service/build.gradle.kts
- backend/auth-service/build.gradle.kts
- backend/indexing-service/api/src/commonMain/kotlin/QueryDescriptions.kt
- backend/indexing-service/build.gradle.kts
- backend/indexing-service/k8.kts
- backend/indexing-service/src/jvmMain/kotlin/indexing/services/ElasticQueryService.kt
- backend/indexing-service/src/jvmMain/kotlin/indexing/util/ElasticUtil.kt
- backend/jvm-provider-support/build.gradle.kts
- backend/kubernetes-monitor-service/build.gradle.kts
- backend/mail-service/build.gradle.kts
- backend/mail-service/src/jvmTest/kotlin/mail/services/MailServiceTest.kt
- backend/mail-service/src/jvmTest/kotlin/mail/services/SettingsServiceTest.kt
- backend/password-reset-service/src/jvmTest/kotlin/password/reset/services/PasswordResetServiceTest.kt
- backend/service-lib-server/build.gradle.kts
- backend/service-lib-server/src/jvmMain/kotlin/micro/FlywayFeature.kt
- backend/storage-service/build.gradle.kts
- backend/webdav-service/build.gradle.kts
Updated depedencies (see #2335 )
Fixes #2348 (updated and added new override functions. Tested by running migrations once. Result "no need for migration" = true)
Fixes #2336 (removed dependency to eskotlin and rewrote code that used it. Tested in dev with same results as previous)
> Dependencies

- backend/app-orchestrator-service/build.gradle.kts
- backend/app-store-service/build.gradle.kts
- backend/mail-service/src/jvmTest/kotlin/mail/services/MailServiceTest.kt
- backend/mail-service/src/jvmTest/kotlin/mail/services/SettingsServiceTest.kt
- backend/password-reset-service/src/jvmTest/kotlin/password/reset/services/PasswordResetServiceTest.kt
- backend/service-lib-server/build.gradle.kts
- backend/service-lib/build.gradle.kts
- frontend-web/webclient/app/Files/QuickLaunch.tsx
fixes #2339 
Includes a few fixes to failing tests + version bumps to jackson because of a version conflict after updating elastic.
> Add timeAllocation to QuickLaunch request

- frontend-web/webclient/app/Login/Login.tsx
Removed ifDev checks and seems to work fine local. Have not been able to check on dev since I cannot build container.
Fixes #1988
> Password reset

- backend/storage-service/src/jvmMain/kotlin/file/services/LimitChecker.kt
.. causing an error when approving grant application with lower requested quota than already assigned to sub-projects.
fixes #2342
> Fixed miscalculation in LimitChecker

- backend/auth-service/api/src/commonMain/kotlin/UserDescriptions.kt
- backend/auth-service/src/jvmMain/kotlin/http/UserController.kt
- frontend-web/webclient/app/Admin/UserCreation.tsx
- frontend-web/webclient/app/Admin/index.d.ts
Added first and last name fields to frontend and made them mandatory.
Backend has change of API (first and last name) but they are nullable.
Fixes #2376
> Update to password user creation

- backend/accounting-service/src/jvmMain/kotlin/Main.kt
- backend/accounting-service/src/jvmMain/kotlin/services/CronJobs.kt
Added config and changes to SQL. Fixes #2374
> Removing licenses (and public ip) from low funds check

- backend/app-store-service/api/src/commonMain/kotlin/api/ApplicationParameter.kt
- backend/app-store-service/src/jvmMain/kotlin/app/store/api/ApplicationDescription.kt
made check on enumarations AppParams. Fixes #2227
> Enumeration default value check on app create

- frontend-web/webclient/app/Admin/AppAauAdmin.tsx
- frontend-web/webclient/app/Project/Grant/GrantApplicationEditor.tsx
Reseting fields in AAU maintainence onClick. Fixes #2304 
Added check for loading on submit in grant applications editor. Disabling when loading. Fixes #2343
> minor fronted issues

- backend/app-orchestrator-service/src/jvmMain/kotlin/services/IngressDao.kt
- backend/app-orchestrator-service/src/jvmMain/kotlin/services/IngressService.kt
Save ingresses/public links as lower-case on creation.
fixes #2350
> Enforce lower-case ingresses

- backend/jvm-provider-support/src/jvmMain/kotlin/UCloudSpringConfig.kt
The PathPatterns didnt match all requests
> Correct matching for requests. Match zero or more directories in a path

- frontend-web/webclient/app/Files/Files.tsx
> Storage 2533

- frontend-web/webclient/app/Files/Files.tsx
- frontend-web/webclient/app/Resource/Browse.tsx
> Fixes #2608

- frontend-web/webclient/app/Files/FavoriteToggle.tsx
Fixes crash when accessing favorite metadata
> Handle undefined entry

- frontend-web/webclient/app/Files/Files.tsx
Add chevron to disk selection, to make it more clear that it can be clicked.
> Storage chevron

- backend/ucloud-data-extraction-service/build.gradle.kts
- backend/ucloud-data-extraction-service/k8.kts
- backend/ucloud-data-extraction-service/src/jvmMain/kotlin/services/DeicReportService.kt
> updated DeiC Report job

- frontend-web/webclient/app/Navigation/Header.tsx
- frontend-web/webclient/app/Search/Search.tsx
- frontend-web/webclient/app/ui-components/Input.tsx
> Fixes #2676

- backend/accounting-service/src/jvmMain/resources/db/migration/V15__AccountingUpgrades.sql
- frontend-web/webclient/app/Dashboard/Dashboard.tsx
> Fixes #2674

- frontend-web/webclient/app/Files/FavoriteToggle.tsx
Should, correctly, fix this issues this time.
> Fixes #2687

- backend/storage-service/src/jvmMain/kotlin/file/Main.kt
- backend/storage-service/src/jvmMain/kotlin/file/Server.kt
- backend/storage-service/src/jvmMain/kotlin/file/services/SyncthingClient.kt
- backend/sync-mounter-service/src/jvmMain/kotlin/services/CLibrary.kt
- backend/sync-mounter-service/src/jvmMain/kotlin/services/MountService.kt
fixes #2651 
fixes #2650 
fixes #2648 
fixes #2628
> Syncthing fixes (master)

- frontend-web/webclient/app/Products/CreateProduct.tsx
A file was missing changed import paths
> Fixes imports missing @/

- backend/alerting-service/build.gradle.kts
- backend/alerting-service/k8.kts
- backend/alerting-service/src/jvmMain/kotlin/alerting/services/ElasticAlerting.kt
- backend/elastic-management-service/build.gradle.kts
- backend/elastic-management-service/k8.kts
- backend/elastic-management-service/src/jvmMain/kotlin/elastic/management/services/ExpiredEntriesDeleteService.kt
- backend/project-service/build.gradle.kts
- backend/project-service/k8.kts
- backend/project-service/src/jvmMain/kotlin/project/services/ProjectService.kt
- backend/ucloud-data-extraction-service/build.gradle.kts
- backend/ucloud-data-extraction-service/k8.kts
- backend/ucloud-data-extraction-service/src/jvmMain/kotlin/Server.kt
- backend/ucloud-data-extraction-service/src/jvmMain/kotlin/services/ElasticDataService.kt
- backend/ucloud-data-extraction-service/src/jvmMain/kotlin/services/PostgresDataService.kt
- backend/ucloud-data-extraction-service/src/jvmMain/kotlin/services/UserActivityReport.kt
Elastic cleanup fix
Project invite fix.
> fixes #2573. Added fix to bulk invito to project from storage branch

- frontend-web/webclient/app/Authentication/DataHook.ts
- frontend-web/webclient/app/Utilities/XHRUtils.ts
- frontend-web/webclient/app/UtilityFunctions.tsx
Removes usage of HTTP_STATUS_CODES and removes any string reference to "Internal Server Error".
> Fixes #2800

- frontend-web/webclient/app/Admin/Providers/Browse.tsx
- frontend-web/webclient/app/Files/Metadata/Templates/Create.tsx
- frontend-web/webclient/app/MainContainer/MainContainer.tsx
- frontend-web/webclient/app/Resource/Browse.tsx
- frontend-web/webclient/app/ui-components/ConfirmationAction.tsx
- frontend-web/webclient/app/ui-components/Operation.tsx
Shake the content of the button, not the button.
> Fixes #2770

- frontend-web/webclient/app/Files/Uploader.tsx
> Storage 2838

- frontend-web/webclient/app/Dashboard/Dashboard.tsx
> Removed padding from child elements in dashboard notifications list

- frontend-web/webclient/app/Applications/Ingresses/Browse.tsx
- frontend-web/webclient/app/Applications/Licenses.tsx
- frontend-web/webclient/app/Applications/NetworkIP/Browse.tsx
Fixes issue #2915 on Resources-page
> Fixed issues related to #2915 in Resources-page

- frontend-web/webclient/app/UserSettings/ChangeEmailSettings.tsx
> Ignore if mail-service is unavailable when entering user settings

- frontend-web/webclient/app/Applications/Ingresses/Browse.tsx
- frontend-web/webclient/app/Applications/Licenses.tsx
> Fixes #2997

- frontend-web/webclient/app/Resource/Filter.tsx
> Change creation date quick-filter from "last" to "past"

- backend/file-orchestrator-service/util/src/jvmMain/kotlin/FileCollectionService.kt
> Fixed sorting by title for drives

- frontend-web/webclient/app/UtilityComponents.tsx
> Added missing margin on namingfield pre/suffixes

- frontend-web/webclient/app/Files/Metadata/Documents/History.tsx
> Disable deletion of 'deleted' metadata document

- frontend-web/webclient/app/Resource/Filter.tsx
- frontend-web/webclient/app/ui-components/ClickableDropdown.tsx
> Minor ui enhancements for filters in modals

- backend/file-orchestrator-service/api/src/commonMain/kotlin/Shares.kt
> Fixed properties of share not showing

- frontend-web/webclient/app/Resource/Browse.tsx
- frontend-web/webclient/app/UCloud/ResourceApi.tsx
> Added cancel button when selecting product on resource creation

- frontend-web/webclient/app/UCloud/ResourceApi.tsx
> Redirect on delete from properties page of resource

- backend/file-orchestrator-service/src/jvmMain/kotlin/service/ShareService.kt
- backend/file-orchestrator-service/util/src/jvmMain/kotlin/FileCollectionService.kt
> Delete share when filecollection is deleted

- frontend-web/webclient/app/Products/Products.tsx
Remove Licenses from SKUs page.
Fix rendering not using the correct page.
> Fixes #3201

- backend/app-orchestrator-service/build.gradle.kts
- backend/app-orchestrator-service/k8.kts
- backend/app-orchestrator-service/src/jvmMain/kotlin/services/JobMonitoringService.kt
Should fix issue so we do not have dates in year 54014
> hotfix for timestamp in jobs

- backend/mail-service/build.gradle.kts
- backend/mail-service/k8.kts
- backend/mail-service/src/jvmMain/kotlin/mail/services/MailService.kt
> Fixes #3162

- frontend-web/webclient/app/Project/ProjectList.tsx
- frontend-web/webclient/app/Resource/Browse.tsx
> Fixes 3061

- frontend-web/webclient/app/Project/Grant/GrantApplicationEditor.tsx
Fixes #2327, at least the issues I could find.
> Fix Application Document not updating on reload

- frontend-web/webclient/app/Project/Grant/IngoingApplications.tsx
- frontend-web/webclient/app/Project/Grant/OutgoingApplications.tsx
- frontend-web/webclient/app/Project/ProjectList.tsx
- frontend-web/webclient/app/Resource/Filter.tsx
> Issue 2923

- frontend-web/webclient/app/Applications/Jobs/Widgets/Reservation.tsx
Removes references to `minutes` in Parameters.
> Fixes #3252

- frontend-web/webclient/app/Admin/Providers/View.tsx
- frontend-web/webclient/app/Products/Products.tsx
Removes Sync as a product to create in providers.
Removes "Synchronization" as a product area in ProductView (/skus/)
> Fixes compile errors added by sync branch

- frontend-web/webclient/app/Applications/Jobs/Create.tsx
- frontend-web/webclient/app/Applications/Jobs/Resources/Folders.tsx
- frontend-web/webclient/app/Applications/Jobs/Resources/Ingress.tsx
- frontend-web/webclient/app/Applications/Jobs/Resources/NetworkIPs.tsx
- frontend-web/webclient/app/Applications/Jobs/Resources/Peers.tsx
- frontend-web/webclient/app/Applications/Jobs/Widgets/ImportParameters.tsx
Also fix typeof matching being done on `undefined` and not `"undefined"`
Fixes #3267, but for more than just Ingress.
> Add resource check on import

- backend/file-ucloud-service/README.md
> Syncthing documentation

- backend/file-ucloud-service/src/jvmMain/kotlin/services/SyncService.kt
fixes #3292 
When stopping sync of a folder, remove it from Syncthing before unmounting.
Also adds some delays, as well as retries to the unmount call, since the folder in question might still be occupied by Syncthing the first time unmount is called.
If we are unable to unmount the folder (after 3 retries), we let it be, but since it was removed from Syncthing it wont be synced anymore. The folder will be unmounted when the service is restarted.
This is not ideal, but a quick fix to prevent an inconsistent state, or a situation where it is not possible to remove a folder from sync due to race conditions between the sync-mounter and syncthing.
> Minor Syncthing fixes

- backend/integration-testing/src/jvmTest/kotlin/e2e/AppTest.kt
- backend/integration-testing/src/jvmTest/kotlin/e2e/JobCreationComponent.kt
- backend/integration-testing/src/jvmTest/kotlin/e2e/StorageTest.kt
- frontend-web/webclient/app/Resource/Browse.tsx
> Update AppTest (remove minutes)

- backend/file-orchestrator-service/src/jvmMain/kotlin/service/SyncFolderService.kt
- frontend-web/webclient/app/Files/Synchronization.tsx
Delete syncfolder if folder is moved to trash
Also adds a warning message to the synchronization modal.
> Handle trashed syncfolders

- backend/file-ucloud-service/src/jvmMain/kotlin/services/SyncService.kt
- backend/file-ucloud-service/src/jvmMain/kotlin/services/SyncthingClient.kt
- Tested multiple instances of Syncthing (as was possible on my local setup). Actual deployment might need adjustments.
- Fixed devices not being written to Syncthing after folder is added
> [sync] Fix write devices after folder is added

- frontend-web/webclient/app/Files/Synchronization.tsx
- frontend-web/webclient/app/UCloud/SyncFolderApi.tsx
> Added warning/info about send-only sync folders

- backend/launcher/src/jvmMain/kotlin/Main.kt
- compose/base.yml
added shares, changed storage to correct format, and made ucloud enabled to apllications
Also added options for ports to synchting in config
> Updates to lancher script

- backend/accounting-service/src/jvmMain/kotlin/services/wallets/AccountingService.kt
- backend/accounting-service/src/jvmMain/resources/db/migration/V30__StorageLockFix.sql
#3350 #3248 #3381 might be fixed.
> Accounting issues fix

- backend/extract-data-service/src/jvmMain/kotlin/Server.kt
- backend/extract-data-service/src/jvmMain/kotlin/services/ElasticDataService.kt
Download logs + start jobs code
> download file logs extraction

- integrated-applications/syncthing/src/main/kotlin/syncthing/SyncthingClient.kt
- integrated-applications/syncthing/src/main/kotlin/syncthing/UCloudConfigService.kt
> Disable auto check for updates in Syncthing app

- frontend-web/webclient/app/Applications/Jobs/Widgets/ImportParameters.tsx
- frontend-web/webclient/app/Project/ProjectList.tsx
- frontend-web/webclient/app/Project/ProjectList2.tsx
- frontend-web/webclient/app/Project/SubAllocations.tsx
Some buttons and text on the page was not consistent with the rest of the site. Changed text case where `Uxxxx Uxxxx` was used instead of `Uxxxx uxxxxx`. Changed `Remove recipient` to `Discard`.
> Fixed casing of some text

- provider-integration/integration-module/src/nativeMain/kotlin/utils/FileUtils.kt
- provider-integration/integration-module/src/nativeMain/kotlin/utils/NativeInputStream.kt
- provider-integration/integration-module/src/nativeMain/kotlin/utils/NativeOutputStream.kt
- provider-integration/integration-module/src/nativeMain/kotlin/utils/execv.kt
> [im-core] file descriptor leak fix

- provider-integration/integration-module/src/nativeMain/kotlin/ipc/IpcPingPong.kt
- provider-integration/integration-module/src/nativeMain/kotlin/ipc/IpcServer.kt
- provider-integration/integration-module/src/nativeMain/kotlin/plugins/SimpleProjectPlugin.kt
Make sure IM/User is restarted in case of any of the user was added/removed from a project or project group.
Fixes #3442
> Restart of IM/User on events

- frontend-web/webclient/app/Applications/Jobs/View.tsx
> Fix frontend crash on job status page when job expires

- frontend-web/webclient/app/Project/Allocations.tsx
- frontend-web/webclient/package-lock.json
- frontend-web/webclient/package.json
> Add missing packages

- provider-integration/integration-module/example-extensions/storage-du-accounting
- provider-integration/integration-module/src/main/kotlin/plugins/storage/posix/PosixCollectionPlugin.kt
- provider-integration/integration-module/src/main/kotlin/plugins/storage/posix/PosixFilesPlugin.kt
- provider-integration/integration-module/src/main/kotlin/utils/GraalLoop.kt
> [im] Posix plugin fixes and accounting

- frontend-web/webclient/app/Dashboard/Dashboard.tsx
- frontend-web/webclient/app/Project/Grant/GrantApplicationEditor.tsx
Some changes based on requests from Claudio.
For new applications, show PI and project name/my workspace at the top.
Hide application text area until grant giver selected.
"New project" button if My Workspace or Existing project as targets.
Write explanation text depending target.
Remove "Apply for resources" from Resource Allocations. Always show on Grant Applications.
Remove empty case for Resource Usage.
Center align text in cards.
Bugs pointed out by @DanThrane 
Filter by usable wallets.
> Grant selection

- provider-integration/integration-module/src/main/kotlin/plugins/storage/posix/PosixCollectionPlugin.kt
> Added missing to_timestamp in insert scan of Posix plugin

- integrated-applications/syncthing/src/main/kotlin/syncthing/SyncthingClient.kt
> Disable fsWatcher (inotify) in Syncthing

- frontend-web/webclient/app/Project/SubAllocations.tsx
The master branch was missing an import.
> Fix missing import

- frontend-web/webclient/app/Playground/Playground.tsx
- frontend-web/webclient/app/ui-components/Error.tsx
- frontend-web/webclient/app/ui-components/SupportBox.tsx
- frontend-web/webclient/app/ui-components/Tooltip.tsx
Shows error is a system is not listed as operational. Removes a bunch of unused code also.
> Fixes #3749

- frontend-web/webclient/app/UCloud/FileCollectionsApi.tsx
My code for calculating support for drive creations was wrong.
> Fix missing create drive button

- frontend-web/webclient/app/Authentication/lib.ts
- frontend-web/webclient/app/Core.tsx
- frontend-web/webclient/app/Files/Preview.tsx
- frontend-web/webclient/app/Login/Login.tsx
- frontend-web/webclient/app/Resource/Router.tsx
- frontend-web/webclient/app/ui-components/Sidebar.tsx
- Fix error caused React 18 upgrade (double-requests) 
- Fix path for properties. Issue when going direct to file properties. 
- Fix ordering of hooks, that React complained about.
Fixes #3420
> Redirect to intended page, when not logged, and then logging in.

- frontend-web/webclient/app/Project/SubAllocations.tsx
> Suballocation bugs 3769

- frontend-web/webclient/app/Applications/Jobs/View.tsx
- frontend-web/webclient/app/UCloud/FilesApi.tsx
- frontend-web/webclient/app/UCloud/JobsApi.tsx
- frontend-web/webclient/app/UCloud/MetadataNamespaceApi.tsx
- frontend-web/webclient/app/UCloud/NetworkIPApi.tsx
- frontend-web/webclient/app/UCloud/ResourceApi.tsx
Some changes to API implementations to conform to the `api<Operation>` approach.
Some calls are untested (these are marked with comments) as I don't have access to them on my local machine. One is seemingly unused.
> Minor refactoring

- frontend-web/webclient/app/Project/Grant/GrantApplicationEditor.tsx
- frontend-web/webclient/app/Project/SubAllocations.tsx
- frontend-web/webclient/app/ui-components/Accordion.tsx
Small UI fixes for Suballocation use of Accordions
> Fixes #3798

- backend/app-orchestrator-service/src/main/kotlin/services/IngressService.kt
- frontend-web/webclient/app/Applications/Jobs/View.tsx
- provider-integration/integration-module/src/main/kotlin/plugins/compute/ucloud/FeatureIngress.kt
- Normalize ingresses on creation (lowercase). (fixes #3347)
- Links in Public Links card on job view page were broken.
- Show proper error message when trying to create a ingress with a domain that already exist.
> Minor ingress fixes and normalization

- frontend-web/webclient/app/Files/Files.tsx
- frontend-web/webclient/package.json
> Fixes #3812

- frontend-web/webclient/app/Files/Files.tsx
- frontend-web/webclient/app/Resource/Browse.tsx
- frontend-web/webclient/app/UCloud/FileCollectionsApi.tsx
Reloads products on project change
Show descriptive text if no resources to create drives for Show text if no drives in project
> Fixes #3804

- frontend-web/webclient/app/Project/Allocations.tsx
Changes how projectOverride is sent
> Fixes #3828

- provider-integration/integration-module/src/main/kotlin/plugins/compute/ucloud/FeatureExpiry.kt
> Corrected fetching of job annotations causing problems with job expiry

- frontend-web/webclient/app/Applications/Jobs/Widgets/ImportParameters.tsx
- frontend-web/webclient/app/Dialog/DialogStore.ts
- frontend-web/webclient/app/MainContainer/MainContainer.tsx
- frontend-web/webclient/app/Project/Members2.tsx
- frontend-web/webclient/app/Project/ProjectSettings.tsx
- frontend-web/webclient/app/Utilities/ModalUtilities.ts
- frontend-web/webclient/app/UtilityComponents.tsx
Changes default modal size for defaultModalStyle.
Adds typesafety for onwheel handling
> Modal size 3819

- backend/accounting-service/src/main/resources/db/migration/V40__RequestedResourceTimeFix.sql
> seconds to millisections on requested resources

- provider-integration/integration-module/src/main/kotlin/plugins/licenses/generic/Plugin.kt
> Mark license as ready on create

- frontend-web/webclient/app/Applications/Jobs/Create.tsx
> Fixes not being able to select machine on Jobs create page

- provider-integration/integration-module/src/main/kotlin/plugins/storage/ucloud/Plugin.kt
- provider-integration/integration-module/src/main/kotlin/plugins/storage/ucloud/TaskSystem.kt
> Fixed task-system in integration-module

- integration-test/build.gradle.kts
- integration-test/src/test/kotlin/utils/Projects.kt
Update to changed API of tests.
> opdate of version to passable tests

- backend/audit-ingestion-service/src/main/kotlin/audit/ingestion/processors/AuditProcessor.kt
assumed nullable variable never was null = crash in runcatching -> no error
> fixes #3998

- provider-integration/integration-module/src/main/kotlin/plugins/puhuri/PuhuriPlugin.kt
> Puhuri API changes

- frontend-web/webclient/app/Files/FileBrowse.tsx
- frontend-web/webclient/app/Grants/Editor.tsx
- frontend-web/webclient/app/UCloud/FilesApi.tsx
> Create folder from files dialog

- backend/accounting-service/src/main/kotlin/services/wallets/AccountingProcessor.kt
Should fix #4069 and fix #4070
> Accountingerrors

- provider-integration/integration-module/src/main/kotlin/plugins/compute/ucloud/FeaturePublicIP.kt
> added check to Ips on jobCreation

- provider-integration/integration-module/src/main/kotlin/plugins/puhuri/PuhuriPlugin.kt
> Changes to PuhuriPlugin according Puhuri API changes

- frontend-web/webclient/app/Files/Shares.tsx
- frontend-web/webclient/app/Files/SharesOutgoing.tsx
- frontend-web/webclient/app/ui-components/Sidebar.tsx
When projects active it will redirect to dashboard when attempting shares view. Also removed shares from sidebar when project active
> fixes #3431 . 

- backend/file-orchestrator-service/src/main/kotlin/service/ShareService.kt
> Fixes 3269 . Should update permissions argument was never used

- provider-integration/integration-module/src/main/kotlin/plugins/storage/ucloud/FileQueries.kt
- provider-integration/integration-module/src/main/kotlin/plugins/storage/ucloud/Plugin.kt
Now finds suitable name on rename policy when creating folders and creates a folder with that name instead.
filename(X) 
X=1..1000
> fixes #3898

- backend/accounting-service/api/src/main/kotlin/AccountingV2.kt
- backend/accounting-service/api/src/main/kotlin/Wallets.kt
- backend/accounting-service/src/main/kotlin/services/wallets/AccountingProcessor.kt
- frontend-web/webclient/app/Accounting/index.ts
- provider-integration/integration-module/src/main/kotlin/plugins/compute/ucloud/FeatureAccounting.kt
- provider-integration/integration-module/src/main/kotlin/plugins/compute/ucloud/JobManagement.kt
- provider-integration/integration-module/src/main/kotlin/utils/AccountingSystem.kt
fixes multiple issues. Fix #4130, made functiont only charge parent tree when current alloc is using less than quota of parent. Fix #4129 Made call to check from IM. Fix #4128 and fix #4127 removed isLocked and replaced by internal function to check parents as well
> Accounting problems fixes

- provider-integration/integration-module/src/main/kotlin/plugins/storage/ucloud/Plugin.kt
Dont know if there is a better way fo getting filecollection
> added check on upload. Fails if quota is exceeded

- backend/app-orchestrator-service/src/main/kotlin/services/JobResourceService.kt
- frontend-web/webclient/app/Applications/PublicLinks/PublicLinkBrowse.tsx
- frontend-web/webclient/app/Applications/SshKeys/SSHKeyBrowse.tsx
- frontend-web/webclient/app/Files/Shares.tsx
- frontend-web/webclient/app/Files/SharesOutgoing.tsx
- frontend-web/webclient/app/Notifications/index.tsx
- frontend-web/webclient/app/Project/ContextSwitcher.tsx
fixes #4185 
- Changed color of context-switcher favorite icons for consistency
- Reduced size of icons on shares pages for consistency
- Prevent submit on creation of public link if field is empty
- Corrected "empty icon" for SSH keys to be correct color, and to use hero icon.
- Notifications for jobs now includes the name of the job (if any), not just the name of the application.
> Minor UI fixes

- provider-integration/integration-module/src/main/kotlin/plugins/storage/ucloud/tasks/CreateFolderTask.kt
> Fixed exception on CreateFolderTask

- backend/notification-service/src/main/kotlin/notification/services/NotificationService.kt
> Stop job notification setting not respected

- frontend-web/webclient/app/Applications/Jobs/View.tsx
Allows adding `ALLOW_JOB_DEBUGGING_INFO` to localStorage, to enable A LOT of debug info to hopefully track down this issue if it re-appears.
> Attempts to fix #4240

- frontend-web/webclient/app/Accounting/Allocations.tsx
- frontend-web/webclient/package-lock.json
- frontend-web/webclient/package.json
> Fixes #4256

- frontend-web/webclient/app/Applications/Jobs/Create.tsx
> Fixes #4275

- backend/accounting-service/src/main/kotlin/services/accounting/System.kt
- backend/accounting-service/src/main/kotlin/services/grants/GrantsV2Service.kt
Debug println( when assigning totalAlllocated
> Debug for total Alloc Error

- frontend-web/webclient/app/Files/FileBrowse.tsx
- frontend-web/webclient/app/Project/ContextSwitcher.tsx
- frontend-web/webclient/app/ui-components/ResourceBrowser.tsx
- frontend-web/webclient/package-lock.json
- frontend-web/webclient/package.json
> Issue 4294

- frontend-web/webclient/app/Playground/Playground.tsx
- frontend-web/webclient/app/ui-components/ConfirmationAction.tsx
- frontend-web/webclient/package-lock.json
- frontend-web/webclient/package.json
> Shows "Hold to confirm" on hover for confirmation actions

- frontend-web/webclient/app/UCloud/FilesApi.tsx
- frontend-web/webclient/app/ui-components/Browse.tsx
New look. While better, I think more should be done at some point. Maybe when doing more with metadata?
> Fixes #4302

- frontend-web/webclient/app/Accounting/Allocations.tsx
Tested on local environment and now looks fine
> Confusing UI in accounting fix

- frontend-web/webclient/app/Grants/Editor.tsx
- frontend-web/webclient/package-lock.json
- frontend-web/webclient/package.json
Adds recipient-type to "AllocatorsLoaded" action, when we have the info fetched already. 
Only changes behavior by a tiny bit where the error has been observed.
> Issue 4220

- frontend-web/webclient/app/Files/FileBrowse.tsx
- frontend-web/webclient/app/ui-components/ResourceBrowser.tsx
Correctly sets width for icon
Clip overflow in modals. Entry still clickable.
> Fixes 4201

- frontend-web/webclient/app/Dashboard/Dashboard.tsx
- frontend-web/webclient/app/ui-components/Dropdown.tsx
- frontend-web/webclient/package-lock.json
- frontend-web/webclient/package.json
Remove unused props for Dropdown.tsx
Update packages
> Fixes #4359

- frontend-web/webclient/app/Files/FileBrowse.tsx
- frontend-web/webclient/app/ui-components/ResourceBrowser.tsx
> Fixes #4366

- backend/app-orchestrator-service/src/main/kotlin/services/JobMonitoringService.kt
- provider-integration/integration-module/src/main/kotlin/plugins/compute/ucloud/JobManagement.kt
Unsure if this is correct approach.
Fewer errors to log due to quota error when restarting (logs every 1 hour instead of every 10 sec). Searches for suspended syncthing instance to get id when attempting to add new folder in case of quota lock. #4292 . Does not create new instance in case of quota issue and therefore no IN_QUEUE.
Log reduction: Not tested
IN_QUEUE error: Tested locally
> Syncthing Quota limit issue

- provider-integration/im2/cmd/ucloud-im/main.go
- provider-integration/im2/pkg/termio/prompts.go
Also improved error handling slightly.
> Changed LoadingIndicator to use pipe

- backend/accounting-service/util/src/main/kotlin/AsyncCache.kt
> invalidates key when entry fails

- frontend-web/webclient/app/Accounting/index.ts
- frontend-web/webclient/app/Files/FavoriteCache.ts
- frontend-web/webclient/app/Files/FavoritesBrowse.tsx
- frontend-web/webclient/app/Project/ContextSwitcher.tsx
Remove console logs
Add false positive to test that may require some fixes to accommodate Rename function to have consistent naming
Fix compiler warning about null-coalescing not making sense (FavoriteBrowse)
Note: Only scrolls on favorites. Does not scroll down on unfavoriting. Don't know if this is a dumb idea.
> Fixes #4385

- frontend-web/webclient/app/Applications/Jobs/JobsBrowse.tsx
- frontend-web/webclient/app/ui-components/ResourceBrowser.tsx
- frontend-web/webclient/app/ui-components/ResourceBrowserFilters.ts
https://github.com/user-attachments/assets/118e0958-3d96-4482-9ffa-546974657e63
> Fixes #4405

- frontend-web/webclient/app/Applications/Group.tsx
- frontend-web/webclient/app/Applications/Overview.tsx
- frontend-web/webclient/app/Applications/Search.tsx
Has the side-effect of widening cards, as this uses MainContainer for consistency.
> Fixes #4418

- frontend-web/webclient/app/Playground/Playground.tsx
- frontend-web/webclient/app/Services/BackgroundTasks/BackgroundTask.tsx
- frontend-web/webclient/app/ui-components/Sidebar.tsx
Adds option to remove entry from finished tasks (only done locally currently)
Sorts finished tasks in same way as in progress tasks
Adds new icon/animation for tasks
Adds empty page for tasks
Always shows task-icon in sidebar
> Task system redo

- backend/accounting-service/src/main/kotlin/services/grants/GrantsV2Service.kt
> fixes #4426

- provider-integration/im2/pkg/apm/accounting.go
- provider-integration/im2/pkg/client/client.go
- provider-integration/im2/pkg/im/controller/job_database.go
- provider-integration/im2/pkg/im/launcher/module.go
- provider-integration/im2/pkg/im/services/slurm/compute.go
- provider-integration/im2/pkg/im/services/slurm/drive_locator.go
- provider-integration/im2/pkg/im/services/slurm/files.go
- provider-integration/im2/pkg/orchestrators/applications.go
- provider-integration/im2/pkg/orchestrators/jobs.go
- provider-integration/im2/pkg/util/arrays.go
> Registration of Slurm jobs

- frontend-web/webclient/app/Files/FileBrowse.tsx
- frontend-web/webclient/app/UCloud/FilesApi.tsx
- frontend-web/webclient/package-lock.json
- frontend-web/webclient/package.json
Omits some operations when in a search context, but adds "Go to parent" operation when in search
Update packages
Minor refactoring
> Fixes #4437

- frontend-web/webclient/app/Applications/Jobs/CatalogDiscoveryMode.tsx
- frontend-web/webclient/app/Login/Login.tsx
- frontend-web/webclient/app/Notifications/index.tsx
- frontend-web/webclient/app/Project/ContextSwitcher.tsx
- frontend-web/webclient/app/Services/BackgroundTasks/BackgroundTask.tsx
- frontend-web/webclient/app/ui-components/ClickableDropdown.tsx
- frontend-web/webclient/app/ui-components/RichSelect.tsx
- frontend-web/webclient/app/ui-components/Sidebar.tsx
- frontend-web/webclient/app/ui-components/SupportBox.tsx
- frontend-web/webclient/site.config.json
Also changes sandbox default login
> Fixes #4457

- frontend-web/README.md
Updates documentation to remove outdated content and describe more current state of the frontend
> Frontend documentation

- frontend-web/webclient/app/Applications/Jobs/View.tsx
Tested adding hours, and letting it tick. Keeps updates local to the new component.
> Minimizes re-renders for Job/View component when running

- frontend-web/webclient/app/Files/FilePath.tsx
- frontend-web/webclient/package-lock.json
- frontend-web/webclient/package.json
> Fixes #4510

- frontend-web/webclient/app/Applications/Jobs/Widgets/Ingress.tsx
- frontend-web/webclient/app/Applications/Jobs/Widgets/License.tsx
- frontend-web/webclient/app/Applications/Jobs/Widgets/NetworkIP.tsx
- frontend-web/webclient/app/Applications/LicenseBrowse.tsx
- frontend-web/webclient/app/Applications/PublicLinks/PublicLinkBrowse.tsx
Also fix license browser setting title when in modal
> Fixes #4496

- frontend-web/webclient/app/Files/Uploader.tsx
> Add error message and state-change when websocket upload fails

- frontend-web/webclient/app/Accounting/Allocations.tsx
- frontend-web/webclient/app/Dashboard/Dashboard.tsx
> Fixes #4539

- frontend-web/webclient/app/Applications/Jobs/Create.tsx
Seems to stop it from crashing and correctly import resources
> Hotfix import issues

- frontend-web/webclient/app/Accounting/index.ts
- frontend-web/webclient/app/Dashboard/Dashboard.tsx
- frontend-web/webclient/app/Vim/vimwasm.ts
Change when over-allocation warnings are shown.
> Change when overallocations warnings appear.

- provider-integration/im2/pkg/termio/ansi.go
- provider-integration/im2/pkg/termio/frame.go
- provider-integration/im2/pkg/termio/table.go
Title, issue present on Hippo for usernames.
> handle width of utf8 symbols in table output

- frontend-web/webclient/app/UCloud/FilesApi.tsx
- provider-integration/im2/pkg/im/services/k8s/filesystem/00_module.go
> Legacy support for file sensitivity for im2-k8s

- frontend-web/webclient/app/Files/Uploader.tsx
Not ideal solution as it's a fixed size, but better than before.
> Fixes #4655

- provider-integration/im2/pkg/im/services/k8s/containers/firewall.go
> Connect to job functionality for im2-k8s

- frontend-web/webclient/app/Editor/Editor.tsx
- frontend-web/webclient/app/UCloud/FilesApi.tsx
I was sure I had already made this PR.
> Fixes #4665, #4664

- launcher-tool/src/main/kotlin/ComposeFile.kt
- provider-integration/integration-module/src/main/kotlin/plugins/storage/ucloud/TaskSystem.kt
- provider-integration/integration-module/src/main/kotlin/plugins/storage/ucloud/tasks/EmptyTrashTask.kt
Lowered delay from 10 sec to 1 sec in case of no task, and increased to 100 coroutines
> Task issue

- frontend-web/webclient/app/Editor/Editor.tsx
- frontend-web/webclient/app/Resource/Properties.tsx
- frontend-web/webclient/app/UCloud/FileCollectionsApi.tsx
- frontend-web/webclient/app/UCloud/FilesApi.tsx
- frontend-web/webclient/app/UCloud/ResourceApi.tsx
- frontend-web/webclient/app/UCloud/SharesApi.tsx
- frontend-web/webclient/app/ui-components/PopIn.tsx
A lot of the changes are whitespace. I'd recommend hiding those changes when viewing the PR.
> Issue 4800

- frontend-web/webclient/app/Accounting/Allocations.tsx
- frontend-web/webclient/app/Accounting/index.ts
- frontend-web/webclient/app/Dashboard/Dashboard.tsx
- frontend-web/webclient/app/Editor/Editor.tsx
- frontend-web/webclient/app/ui-components/Progress.tsx
Fixes #4903, #4900 
#4900:
#4903:
old:
new:
old:
new:
> Usage and editor issues

- frontend-web/webclient/app/Files/DriveBrowse.tsx
- frontend-web/webclient/app/Files/FileBrowse.tsx
- frontend-web/webclient/app/Files/SharesOutgoing.tsx
- frontend-web/webclient/app/Notifications/Popups.tsx
- frontend-web/webclient/app/Notifications/Snooze.ts
- frontend-web/webclient/app/Notifications/index.tsx
- frontend-web/webclient/app/Providers/ConnectionState.tsx
- frontend-web/webclient/app/Routes.ts
- frontend-web/webclient/package-lock.json
- frontend-web/webclient/package.json
Quicktime doesn't show it, but it does change into a pointer cursor on hover
https://github.com/user-attachments/assets/d53ab601-adb0-481d-8956-8f136903597e
> Fixes #4796

- frontend-web/webclient/app/Files/FileBrowse.tsx
- frontend-web/webclient/app/UCloud/FilesApi.tsx
https://github.com/user-attachments/assets/2bbf97fb-a83e-458f-b0ac-ff795d2dc8c7
> issue #3774

- frontend-web/webclient/app/Applications/Jobs/Widgets/Workflow.tsx
- frontend-web/webclient/app/Applications/Workflows/Editor.tsx
- frontend-web/webclient/app/Authentication/HttpClientInstance.ts
- frontend-web/webclient/app/Editor/Editor.tsx
- frontend-web/webclient/package-lock.json
Fixes #4957
Fixes #4739 
Some other small fixes that you'd rarely run into.
> Editor issues

- frontend-web/webclient/app/Files/DriveBrowse.tsx
- frontend-web/webclient/app/ui-components/ResourceBrowser.tsx
Remove unused variables and imports
> Fixes #4982
